name: Publish FluentRedditSearch

on:
  push:
    branches: [ master ]

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore
      working-directory: src

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src

    - name: Test
      run: dotnet test -restore:False
      working-directory: src/FluentRedditSearch.Tests

    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/FluentRedditSearch/FluentRedditSearch.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}